[package]
name = "rust-panel"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
crossterm = "0.29.0"
env = "1.0.1"
figlet-rs = "0.1.5"
ratatui = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.20"
